name 'brandocorp-website'
maintainer 'Brandon Raabe'
maintainer_email 'brandocorp@gmail.com'
license 'mit'
description 'Installs/Configures brandocorp-website'
long_description 'Installs/Configures brandocorp-website'
version '0.1.0'
