platform: linux

image_resource:
  type: docker-image
  source:
    repository: brandocorp/chefdk
    tag: latest

inputs:
  - name: apache2
  - name: brandocorp-website

params:
  cookbook: community-cookbook

run:
  path: ci/scripts/update-dependency-cookbook.sh
